# Run this using following command on root repo dir. Note that this doesn't clone repo, instead mounts existing dir into drone containers.
# drone exec --timeout "1h0m0s" --timeout.inactivity "0h45m0s" --repo.trusted .drone.local.yml
---
workspace:
  base: /go
  path: src/github.com/vmware/vic-product

pipeline:
  unified-ova-build: 
    image: gcr.io/eminent-nation-87317/vic-product-build:latest
    pull: true
    privileged: true
    environment:
      ADMIRAL: ${ADMIRAL}
      BUILD_ADMIRAL_RELEASE: ${BUILD_ADMIRAL_RELEASE}
      BUILD_VICENGINE_REVISION: ${BUILD_VICENGINE_REVISION}
      DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
      DRONE_TIMEOUT: ${DRONE_TIMEOUT}
      DRONE_TIMEOUT_INACTIVITY: ${DRONE_TIMEOUT_INACTIVITY}
      HARBOR: ${HARBOR}
      TERM: xterm
      VICENGINE: ${VICENGINE}
    volumes:
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - installer/scripts/ci-build.sh
    when:
      repo: vmware/vic-product
      event: [ push, tag ]
      branch: [ master, releases/*, refs/tags/* ]
      status: success
